version: "3"

services:
  bot_feed:
    container_name: bot_feed
    command: python3 app/main.py
    stdin_open: true # docker run -i
    tty: true
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./data:/data/
      - ./sessions:/session
    sysctls:
        - net.ipv4.tcp_keepalive_time=10
        - net.ipv4.tcp_keepalive_intvl=10
        - net.ipv4.tcp_keepalive_probes=5
